source "https://rubygems.org"

gem "rails", "4.2.0"
gem "pg"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "faraday", "< 0.9.0"
gem "pry"
gem "figaro"
gem "active_model_serializers"
gem "responders"
gem "will_paginate", "~> 3.0.6"

gem 'rails_12factor', group: :production

group :development, :test do
  gem "byebug"
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "better_errors"
  gem "binding_of_caller"
  gem "minitest-emoji"
end

group :test do
  gem "vcr"
  gem "webmock"
end
